### ISSUE TITLE
Подключение встроенных библиотек

### ISSUE THREAD

**Issue by Nikita-ip916** [Nikita-ip916/Fifteen#10]
- iostream;

- fstream;

- ctime;

DoD: Встроенные библиотеки корректно выполняют свои функции и не вызывают ошибок.

**Comment by synthicated** [comment]
Задача выполнена:
- Библиотека iostream работает корректно, осуществляет процессы ввода/вывода данных.
- Библиотека fstream работает корректно при работе с файлом, чтении и записи данных (см. issue-8)
- Библиотека ctime выполняет свою роль корректно при генерации чисел, осуществляет случайность генерации. (см. issue-4)
