### ISSUE TITLE
Генерация чисел

### ISSUE THREAD

**Issue by Nikita-ip916** [Nikita-ip916/Fifteen#4]
- Заполнение матрицы случайными числами;

- Предупреждение ситуаций, когда пазл не решается;

DoD: Матрица при каждой новой компиляции собирает разную последовательность чисел, у которой возможно решение.

**Comment by synthicated** [comment]
Задача решена. Описание решения:
В наличии 2 функции.

- Функция `generateArray` отвечает за генерацию чисел (исходной позиции).
- Функция `checkGeneration` отвечает за проверку генерации.
